# Generated by Django 6.1.1 on 2026-09-07 09:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('devices', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DeviceType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='اسم/رمز نوع الجهاز، مثال: النوع A', max_length=100, unique=True)),
                ('description', models.TextField(blank=True)),
                ('setup_schema', models.JSONField(blank=True, default=dict, help_text='تعريف مرن لحقول إعداد هذا النوع، يُملأ لاحقًا بعد تحديد الحقول')),
                ('is_active', models.BooleanField(default=True, help_text='لإخفاء نوع قديم دون حذفه إذا توقف استخدامه')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.AddField(
            model_name='device',
            name='device_type',
            field=models.ForeignKey(blank=True, help_text='نوع الجهاز، يحدد شكل حقول الإعداد الخاصة به', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='devices', to='devices.devicetype'),
        ),
    ]
