# Generated by Django 6.1.1 on 2026-09-26 08:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('devices', '0002_devicetype_device_device_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='device',
            name='model_name',
        ),
        migrations.RemoveField(
            model_name='device',
            name='notes',
        ),
    ]
