# Generated by Django 6.1.1 on 2026-09-07 09:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cases', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='case',
            name='device_setup_parameters',
            field=models.JSONField(blank=True, default=dict, help_text='إعدادات الجهاز الخاصة بهذه الحالة (حسب نوع الجهاز المختار)'),
        ),
    ]
