# Generated by Django 6.1.1 on 2026-09-08 09:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cases', '0002_case_device_setup_parameters'),
    ]

    operations = [
        migrations.AddField(
            model_name='case',
            name='current_medications',
            field=models.TextField(blank=True, help_text='الأدوية المستخدمة حالياً (نص حر)'),
        ),
        migrations.AddField(
            model_name='case',
            name='episode_duration_minutes',
            field=models.PositiveIntegerField(blank=True, help_text='متوسط مدة النوبة بالدقائق', null=True),
        ),
        migrations.AddField(
            model_name='case',
            name='weekly_episode_count',
            field=models.PositiveIntegerField(blank=True, help_text='عدد النوبات في الأسبوع', null=True),
        ),
    ]
