# Generated by Django 6.1.1 on 2026-09-08 09:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cases', '0003_case_current_medications_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='case',
            name='guarantor_address',
            field=models.CharField(blank=True, help_text="Guarantor's address", max_length=255),
        ),
        migrations.AddField(
            model_name='case',
            name='guarantor_email',
            field=models.EmailField(blank=True, help_text="Guarantor's email address", max_length=254),
        ),
        migrations.AddField(
            model_name='case',
            name='guarantor_name',
            field=models.CharField(blank=True, help_text="Guarantor's full name", max_length=150),
        ),
        migrations.AddField(
            model_name='case',
            name='guarantor_phone_number',
            field=models.CharField(blank=True, help_text="Guarantor's phone number", max_length=20),
        ),
        migrations.AlterField(
            model_name='case',
            name='diagnosis_type',
            field=models.CharField(choices=[('migraine', 'Migraine'), ('epilepsy', 'Epilepsy'), ('parkinson', "Parkinson's Disease"), ('depression', 'Depression'), ('other', 'Other')], max_length=20),
        ),
    ]
