# Generated by Django 6.1.1 on 2026-09-19 09:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cases', '0004_case_guarantor_address_case_guarantor_email_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='case',
            name='total_sessions_planned',
            field=models.PositiveIntegerField(blank=True, help_text='العدد الإجمالي المخطط لجلسات العلاج', null=True),
        ),
    ]
