# Generated by Django 6.1.1 on 2026-09-19 15:06

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cases', '0005_case_total_sessions_planned'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CaseProgressNote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('note', models.TextField(help_text='نص حر يكتبه الطبيب لوصف التطور الملاحَظ')),
                ('sessions_completed_snapshot', models.PositiveIntegerField(help_text='عدد الجلسات المكتملة وقت كتابة الملاحظة (لقطة تلقائية)')),
                ('total_sessions_planned_snapshot', models.PositiveIntegerField(blank=True, help_text='العدد الإجمالي المخطط وقت كتابة الملاحظة (لقطة تلقائية)', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('author', models.ForeignKey(help_text='الطبيب الذي كتب هذه الملاحظة', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='case_progress_notes_written', to=settings.AUTH_USER_MODEL)),
                ('case', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='progress_notes', to='cases.case')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
