# Generated by Django 6.1.1 on 2026-09-23 07:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cases', '0008_alter_case_disease_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='WeeklyEpisodeLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('week_start_date', models.DateField(help_text='تاريخ يوم الاثنين لبداية الأسبوع الذي يخص هذا التقرير')),
                ('episode_count', models.PositiveIntegerField(help_text='عدد النوبات التي أجاب بها المريض عن هذا الأسبوع')),
                ('submitted_at', models.DateTimeField(auto_now_add=True)),
                ('case', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='weekly_episode_logs', to='cases.case')),
            ],
            options={
                'ordering': ['week_start_date'],
                'unique_together': {('case', 'week_start_date')},
            },
        ),
    ]
