# Generated by Django 6.1.1 on 2026-09-27 18:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cases', '0009_weekly_episode_log'),
    ]

    operations = [
        migrations.AlterField(
            model_name='case',
            name='disease_type',
            field=models.CharField(blank=True, choices=[('focal', 'Focal Epilepsy'), ('generalized', 'Generalized Epilepsy'), ('combined', 'Combined Generalized and Focal Epilepsy'), ('unknown', 'Unknown Epilepsy'), ('without_aura', 'Migraine without Aura'), ('with_aura', 'Migraine with Aura'), ('chronic', 'Chronic Migraine'), ('menstrual', 'Menstrual Migraine'), ('vestibular', 'Vestibular Migraine')], help_text='نوع/تصنيف فرعي للمرض — يعتمد على diagnosis_type (انظر DISEASE_TYPE_CHOICES_BY_DIAGNOSIS)', max_length=20),
        ),
    ]
