# Generated by Django 6.1.1 on 2026-09-03 18:25

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cases', '0001_initial'),
        ('devices', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TreatmentSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_date', models.DateTimeField()),
                ('duration_minutes', models.PositiveIntegerField(blank=True, null=True)),
                ('device_parameters', models.JSONField(blank=True, default=dict, help_text='إعدادات الجهاز أثناء هذه الجلسة')),
                ('doctor_notes', models.TextField(blank=True)),
                ('patient_response', models.TextField(blank=True, help_text='استجابة/شكوى المريض المسجّلة خلال الجلسة')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('case', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sessions', to='cases.case')),
                ('device', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sessions', to='devices.device')),
                ('performed_by', models.ForeignKey(help_text='الطبيب أو المهندس الذي نفّذ/أشرف على الجلسة', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sessions_performed', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-session_date'],
            },
        ),
    ]
