# Generated by Django 6.1.1 on 2026-09-26 19:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AppVersion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('platform', models.CharField(choices=[('android', 'Android'), ('ios', 'iOS')], default='android', max_length=10)),
                ('version_name', models.CharField(help_text='مثال: 1.4.0 — نص وصفي يُعرض للمستخدم فقط', max_length=30)),
                ('version_code', models.PositiveIntegerField(help_text='رقم صحيح يزداد مع كل إصدار (يطابق versionCode في Android). هذا هو الرقم الذي تتم المقارنة عليه، وليس version_name.')),
                ('release_notes', models.TextField(blank=True, help_text='ماذا تغيّر في هذه النسخة — يُعرض للمستخدم في نافذة التحديث')),
                ('is_mandatory', models.BooleanField(default=False, help_text='إذا فُعّل: يمنع المستخدم من متابعة استخدام التطبيق قبل التحديث')),
                ('apk_file', models.FileField(blank=True, help_text='ملف APK ليُحمَّل مباشرة من التطبيق (اختياري)', null=True, upload_to='app_releases/')),
                ('download_url', models.URLField(blank=True, help_text='رابط خارجي للتحديث (Google Play مثلاً) — يُستخدم إن لم يُرفع ملف APK')),
                ('is_published', models.BooleanField(default=False, help_text='لا تظهر هذه النسخة للمستخدمين إلا بعد تفعيل هذا الخيار')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-version_code'],
            },
        ),
    ]
